services:
    app:
        build: .
        ports:
            - "8080:8080"
        environment:
            MONGODB_URI: mongodb://mongodb:27017/test
            REDIS_HOST: redis
            REDIS_PORT: 6379
            SPRING_PROFILES_ACTIVE: prod
        depends_on:
            - mongodb
            - redis

    mongodb:
        image: mongodb/mongodb-community-server:latest
        ports:
            - "27017:27017"

    redis:
        image: redis:latest
        ports:
            - "6379:6379"
